### PR TITLE
Fix draft parameters

### PR DESCRIPTION
**Pull request by albertobissacco**
Draft accept "before_id" and not "offset" parameter (https://www.tumblr.com/docs/en/api/v2#blog-drafts)
TODO: edit test

### CODE REVIEW

**Comment by meissadia** [comment]
Any chance this fix will be merged? I have the fix  implemented on my machine but would like users of my own project, based on this gem, to not have to hack anything. Thanks!

**Comment by ceyko** [comment]
@albertobissacco Thanks for the PR! If you can please agree to our [CLA](http://static.tumblr.com/zyubucd/GaTngbrpr/tumblr_corporate_contributor_license_agreement_v1__10-7-14.pdf), I'd be happy to merge this.

cc @meissadia

**Comment by albertobissacco** [comment]
Ok

**Comment by ceyko** [comment]
Thanks @albertobissacco!

**Pull request merged**
